Mandy patch2
pnnl/chgl pull request #57
Opened 2019-04-23 16:40 UTC by mandysack

New pull request as requested, this pull request does not include the updates to the mandysack-patch branch, but is rather a new branch.

2019-04-23 20:14 UTC, LouisJenkinsCS requested changes

2019-04-23 20:14 UTC, LouisJenkinsCS commented on src/modules/Components.chpl
> +             return currId;
Can you explain the reasoning behind this change?

2019-04-24 11:13 UTC, mandysack commented
@LouisJenkins, it seems that I do not have permissions to reply to #57 comment....

The reason for adding those 2 lines in Components.chpl is to remove the seg fault that occurs when you have multiple files. At some point it will finish checking for neighbors and won't have anything else to read in, and if you don't do a check prior to reading it, the program seg faults.

2019-04-24 11:27 UTC, LouisJenkinsCS commented
@mandysack can you verify that the connected components output are the same as before? I can see that by stopping early, we still mark all edges as being an individual component, and then if it's neighbors have a lesser priority we still claim ownership, and if they have higher priority, we still help the higher priority component... but I'm beginning to doubt the original implementation a bit.

2019-04-24 11:33 UTC, LouisJenkinsCS commented
Yes... so if `retID == currID` we 'help' the task by updating `currID` but we never set the current edge component to the new `currID`. @mandysack if you add logic to compareExchange the current edge's component id if it is lesser than the original, will that work? Sorry to make you do this extra work; if you can't I'll try to do so later today myself.

2019-04-24 11:34 UTC, mandysack commented
No problem, I will have it completed by later this morning for you to review.

2019-04-24 17:07 UTC, mandysack commented
There was logic put in to check to if the eid <= currId after the e.id was read in. The read in part is what creates the seg fault because there isn't anything to read in. 

I added logic to check to see if there was anything else read in first. If there was not then the eid = currId and then will go into the else statement of eid <= currId meaning that the edge has been explored and it will return the eid.

2019-04-24 17:23 UTC, LouisJenkinsCS commented
The thing is, `read` is a call to load the atomic variable, it's not possible for there to be nothing to 'read in'. `if component[e.id].read() == max(int(64))` is equivalent to `if component[e.id] == max(int(64))`, as in a normal array access. Does that make sense? If so, how is it possible that it has nothing else that it can 'read in'

2019-04-24 17:27 UTC, mandysack commented
If it is like an normal array access then I would compare it to an array out of bounds access. When it has nothing else to access, reaching the end of the array, it would lead to an error to attempt to access an array element that didn't exist.

2019-04-24 17:34 UTC, mandysack commented
The changes I added are similar to the logic added the function:
proc getEdgeComponentMappings(graph, s = 1) {

Here it was also getting a seg fault when it would try to component.read() == max(int) which is why it returns a -1 instead of reading the component upon return. 

The changes here check if component[e.id].read() ==max(int) and if they do then it sets the eid = currId 
otherwise it will eid = components[e.id].read() this will then allow you to be able to get into the else statement where you indicate that the edge has already been explored.
return [component in components] if component.read() == max(int) then -1 else component.read();

2019-04-24 18:11 UTC, mandysack commented
@LouisJenkinsCS I am not sure if you are looking at the original change in Components .chpl- but this are the changes that are being proposed in this PR.

          //check to see if there is anything else to read in
          if components[e.id].read() == max(int){
            //we've already explored this edge
            var eid = currId;
          }
          else{
            var eid = components[e.id].read();
          }

2019-04-24 18:30 UTC, LouisJenkinsCS commented
> If it is like an normal array access then I would compare it to an array out of bounds access. When it has nothing else to access, reaching the end of the array, it would lead to an error to attempt to access an array element that didn't exist.

However, `components` mapped over the same domain that the graph is allocated on:

https://github.com/pnnl/chgl/blob/5a39a698fc0075ea44f17316ddcd7675219267ff/src/modules/Components.chpl#L55

As well, `e` is obtained from `graph.walk`:

https://github.com/pnnl/chgl/blob/5a39a698fc0075ea44f17316ddcd7675219267ff/src/modules/Components.chpl#L89-L91

Which walks over edges it is incident on:

https://github.com/pnnl/chgl/blob/5a39a698fc0075ea44f17316ddcd7675219267ff/src/modules/AdjListHyperGraph.chpl#L853-L861

Which implies an out-of-bounds issue somewhere in the graph; if this were the case, you could compile and run without `--fast` and it should throw an out-of-bounds error. I doubt this is the case however.

Later note that if `eid > currId`, it will try to claim that edge in its current component, and if `eid == max(int)` it will always be the case that `eid > currId` 

> otherwise it will eid = components[e.id].read() this will then allow you to be able to get into the else statement where you indicate that the edge has already been explored.

I'm a bit confused here. We initialize all components to `max(int)` so that they are of the lowest priority:

https://github.com/pnnl/chgl/blob/5a39a698fc0075ea44f17316ddcd7675219267ff/src/modules/Components.chpl#L60

If `components[e.id].read() == max(int)` it means it was _not_ explored, hence it should never reach that statement if has not yet been explored.

2019-04-24 18:34 UTC, LouisJenkinsCS commented
I think the confusion is this statement which you mentioned above: https://github.com/pnnl/chgl/blob/5a39a698fc0075ea44f17316ddcd7675219267ff/src/modules/Components.chpl#L110

The only time that `components[e.id] == max(int(64))` at the end of the algorithm is if it was not eligible to be included in a component, I.E it's s-connectivity is less than the passed argument `s`. Does this clear things up? 

By the way if you have a small reproducer dataset I can try to debug the problem myself (as the issue may be occurring somewhere else in the code)

2019-04-24 18:34 UTC, LouisJenkinsCS commented
Finally, sorry to make you do all of this work @mandysack

2019-04-26 19:05 UTC, LouisJenkinsCS commented
@mandysack Can you either further justify that change in Components? That or can you remove those changes so I can merge the rest?

2019-04-30 11:00 UTC, mandysack commented
@LouisJenkinsCS it looks like I have removed the Components.chpl changes back to original. I hope to revisit sometime this week.

2019-04-30 11:24 UTC, LouisJenkinsCS commented
If you can revert all changes to Component.chpl I can merge your other changes as is and let you make a separate PR @mandysack.

2019-04-30 11:29 UTC, mandysack commented
@LouisJenkinsCS I believe I reverted them all now...

2019-04-30 14:34 UTC, merged